### ISSUE TITLE
Need help upgrading from 3.0.0 to 4.0.2

### ISSUE THREAD

**Issue by MorningSleeper** [joeattardi/emoji-button#83]
I need to load your script locally, when I do so with 3.0.0 like:

`<script src="/scripts/emoji-button-3.0.0.min.js" /></script>`

everything works fine in the latest Chrome and Firefox. When I load 4.0.2 the same way I get the following error.

`Uncaught TypeError: emojiPickerMessage.togglePicker is not a function at HTMLInputElement.<anonymous>`

Does that mean the EmojiButton object is not getting created in the emojiPickerMessage variable like it is in 3.0.0? Appreciate any assistance to get it working with 4.0.2. My current code is below, old code that works is the same other than loading version 3.0.0 of the script.

HTML page

```
<script src="/scripts/emoji-button-4.0.2.min.js" /></script>
<input class="divNoBorder " type="button" id="emojiButtonMessage" value="🙂">
```

Javascript file

```
    var emojiPickerMessage = new EmojiButton({
      recentsCount: 50,
      initialCategory: 'recents'
    });

    var emojiButtonMessage = document.getElementById('emojiButtonMessage');

    emojiButtonMessage.addEventListener('click', () => {
      emojiPickerMessage.togglePicker(emojiButtonMessage); // <== error
    });

    emojiPickerMessage.on('emoji', emoji => {
      document.getElementById('saMessage').value += emoji;
    });
```

**Comment by Justsnoopy30** [comment]
The cause is because you are trying to load this with a legacy script tag instead of importing it as a module.

**Comment by Justsnoopy30** [comment]
Instead, create a new JavaScript file an load it with a script tag, but with type=module. Then, import the EmojiButton in your module by using `import EmojiButton from ./scripts/emoji-button-4.0.2.min.js`. After that, you should be able to instantiate the emoji button.

**Comment by MorningSleeper** [comment]
Thanks for the reply, I tried adding type="module" to script tag like:

`<script type="module" src="/scripts/emoji-button-4.0.2.min.js" /></script>`

and in Javascript file added

`import { EmojiButton } from ./scripts/emoji-button-4.0.2.min.js`

but get the following error for that line

`Uncaught SyntaxError: Cannot use import statement outside a module`

**Comment by Justsnoopy30** [comment]
Nono...you need to remove the script tag referring to the emoji button js file, make a new js file with the import syntax I talked about, and make a new script tag that is type="module" pointing to the new js file with the import syntax.

**Comment by Justsnoopy30** [comment]
Or looking at your current code... to be simpler and easier, you could just change that script tag to point to your js file, not emoji button.

**Comment by MorningSleeper** [comment]
Ok, I created a new Javascript file named importEmojiFile.js containing

`import { EmojiButton } from ./scripts/emoji-button-4.0.2.min.js`

Changed script tag to 

`<script type="module" src="/scripts/importEmojiFile.js" /></script>`

and get the following error

`The requested module '/scripts/emoji-button-4.0.2.min.js' does not provide an export named 'EmojiButton'`

**Comment by Justsnoopy30** [comment]
Hmm... try removing the brackets in { EmojiButton} to just use EmojiButton.

**Comment by MorningSleeper** [comment]
The error message just changes to `...does not provide an export named 'default'`

**Comment by joeattardi** [comment]
That's not right. The file should have a named export called `EmojiButton`. Let me do a quick test, I hope I didn't break this release 😄

**Comment by joeattardi** [comment]
It should be working, I just did a minimal example:

```html
<script type="module">
  import { EmojiButton } from 'https://unpkg.com/@joeattardi/emoji-button@4.0.2/dist/index.js';
  
  const trigger = document.querySelector('#trigger');
  
  const picker = new EmojiButton();
  
  trigger.addEventListener('click', () => {
     picker.togglePicker(trigger);
  });
</script>

Where did you get the `emoji-button-4.0.2.min.js` file from?
```

**Comment by MorningSleeper** [comment]
I saved it from https://cdn.jsdelivr.net/npm/@joeattardi/emoji-button@4.0.2/dist/index.min.js

**Comment by joeattardi** [comment]
Not sure why that isn't working. If you look at the very last piece of the minified script, you'll see the named export:

```javascript
export{rn as EmojiButton};
```

**Comment by joeattardi** [comment]
Can you try loading it from the CDN in your `script` tag? Don't know if that will make a difference but it's worth trying.

**Comment by MorningSleeper** [comment]
I am not very knowledgable on any of this but based on your code above, I tried the following in pages header.

```
<script type="module">
import { EmojiButton } from 'https://cdn.jsdelivr.net/npm/@joeattardi/emoji-button@4.0.2/dist/index.min.js';
</script>
```
I then load another script file like

`<script type="text/javascript" src="/scripts/scheduledAlerts.js" /></script>`

which contains a lot of code including

`var emojiPickerMessage = new EmojiButton();`

and I get the following error referencing above line

`ReferenceError: EmojiButton is not defined`

If I move the following

`var emojiPickerMessage = new EmojiButton();`

from the separate file and put it into 

```
<script type="module">
import { EmojiButton } from 'https://cdn.jsdelivr.net/npm/@joeattardi/emoji-button@4.0.2/dist/index.min.js';
var emojiPickerMessage = new EmojiButton();
</script>
```
I don't get the error so I guess it is because it is inside of the module script tag as it is in yours? Same result whether loaded locally or from CDN. I would like to load your script in one script tag and the rest of the code in another like I could in 3.0.0. Is there a way to separate them or do they all have to be grouped together?

**Comment by joeattardi** [comment]
Ah, yes. I should make the documentation clearer - in 3.x, `EmojiButton` was set as a global on the `window` object, but starting with version 4, it's an ES module.

That scrolling behavior doesn't sound good. I can look into that.

**Comment by joeattardi** [comment]
What are you using for the `position` option?

**Comment by MorningSleeper** [comment]
Gotcha, I am new to modules so did not realize that.

Regarding the issue of a page jumping to top, I am using a position of bottom, which does align the picker correctly to the bottom of the element where it is clicked. Tried auto as well. In either case, the page jumps to top when clicking the emoji to pop open the picker putting the picker, which on my page is near bottom of long page, out of sight until one scrolls back down. On your demo page it only seems to happen on the first click while on my pages it seems to happen a few times for some reason.

**Comment by guangzan** [comment]
> Ah, yes. I should make the documentation clearer - in 3.x, was set as a global on the object, but starting with version 4, it's an ES module.`EmojiButton``window`

It's really cool ! I have a question. I hope not to abandon the original way. How can I pack one myself? Using the module will make the final package file of my project too large, and I introduced many dependencies in the form of CDN. And one of the benefits is that it's easier for others to try your project. Thanks！

**Comment by joeattardi** [comment]
I just released a new version, 4.0.3 which should fix the scroll jump issue. Can you retest with the latest release and see if you still have the problem?

I'll leave the issue open for now. Thanks!

**Comment by MorningSleeper** [comment]
Tested with 4.0.3 and issue no longer occurs, thanks!

**Comment by joeattardi** [comment]
Glad to hear it! I will close the issue then. Feel free to re-open or open a new one if you have more issues. Thanks!
